version: '3.8'
services:
  main_graphql_api_server:
    image: main_api_server:b0.2
    ports:
      - "4000:4000"
    volumes:
      - ~/media_data/:/media_data/
    environment:
      MEDIA_QUALITY_ENHANCEMENT_SERVICE_ADDR: media_quality_enhancement_service:4001
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      SECRET: $SECRET
    restart: always
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/memories_db/:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PW